Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.fileUploadBucketName}
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
              - PUT
              - HEAD
            AllowedOrigins:
              - '*'
