Resources:
    DeploymentBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: ${self:custom.deploymentBucketName}

    UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ShopsSqs
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH

    MessageTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: MessagesSqs
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH

    MyQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: RedistributionQueue
