singleQuote: true
jsxSingleQuote: true
trailingComma: "all"
tabWidth: 4
useTabs: true
endOfLine": "auto"
importOrderSeparation: true
importOrderParserPlugins: ["classProperties", "typescript", "jsx"]
importOrder: [
  "<THIRD_PARTY_MODULES>",
  "^@/aws/(.*)$",
  "^@/consts/(.*)$",
  "^@/enums/(.*)$",
  "^@/lambdas/(.*)$",
  "^@/middlewares/(.*)$",
  "^@/repositories/(.*)$",
  "^@/types/(.*)$",
  "^@/utils/(.*)$",
  "^@/validators/(.*)$",
  "^@/(.*)$",
  "^[./]",
]
