module.exports = {
  START_WORKING_DAY: 10,
  END_WORKING_DAY: 19,

  PRICE_PER_CHARACTER: 0.05,
  MIN_PRICE_PER_CHARACTER: 50,
  PRICE_PER_CHARACTER_EN: 0.12,
  MIN_PRICE_PER_CHARACTER_EN: 120,

  MIN_TIME_TEXT_EDITING: 60, // 60 min
  START_TIME_TEXT_EDITING: 30, // 30 min
  CHARACTER_PER_HOUR: 1333,
  CHARACTER_PER_HOUR_EN: 333,
};
