service: northwind-traders

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  stage: ${opt:stage, "dev"}
  fileUploadBucketName: ${self:custom.stage}-upload-northwind-traders

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${self:custom.stage}
  region: us-east-1
  environment:
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileUploadBucketName}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${self:custom.fileUploadBucketName}/*

functions: ${file(serverless/functions.yml)}
resources: ${file(serverless/resources.yml)}
